### ISSUE TITLE
Replace all path.exists with fs.exists to enable working with Node 4.1.1

### ISSUE THREAD

**Issue by wsirota** [calatrava/calatrava#107]
following directions in "Getting Started" - rake web:apache:start fails with following:
coffee web/app/source/bridge.coffee -> /Users/wsirota/Documents/calaPhone1/web/public/scripts
TypeError: path.exists is not a function
    at writeJs (/Users/wsirota/Documents/calaPhone1/node_modules/coffee-script/lib/coffee-script/command.js:356:17)
    at compileScript (/Users/wsirota/Documents/calaPhone1/node_modules/coffee-script/lib/coffee-script/command.js:145:18)
    at /Users/wsirota/Documents/calaPhone1/node_modules/coffee-script/lib/coffee-script/command.js:110:18
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)
rake aborted!
Error compiling CoffeeScript: 'web/app/source/bridge.coffee'

Replacing all "path.exists(" strings with "fs.exists(" fixes the issue locally 
(the web server starts, at least - there is still an error when conversion is attempted: Currency conversation API failed (404) - but that is a separate issue)
